include:
  - remote: 'https://gitlab.freedesktop.org/freedesktop/ci-templates/-/raw/77c0baf9e375ef9d2339148bf3ee0a27313c26ec/templates/fedora.yml'

stages:
 - prep
 - review
 - build
 - test
 - coverage

.mutter.fedora:33@common:
  variables:
    FDO_DISTRIBUTION_VERSION: 33
    FDO_UPSTREAM_REPO: jadahl/mutter
    FDO_DISTRIBUTION_EXEC: |
      dnf install -y 'dnf-command(builddep)' &&
      dnf builddep -y mutter --setopt=install_weak_deps=False &&

      # For running unit tests
      dnf install -y xorg-x11-server-Xvfb mesa-dri-drivers dbus dbus-x11 \
                     xorg-x11-server-Xvfb accountsservice-libs \
                     gnome-control-center gcovr libnma python3-gobject \
                     python3-dbusmock &&

      # GNOME Shell
      dnf builddep -y gnome-shell --setopt=install_weak_deps=False &&
      dnf remove -y gnome-bluetooth-libs-devel &&
      dnf remove -y --noautoremove mutter mutter-devel &&

      dnf clean all

.mutter.fedora:33@x86_64:
  extends: .mutter.fedora:33@common
  variables:
    FDO_DISTRIBUTION_TAG: 'x86_64-2020-11-07.0'

.mutter.fedora:33@aarch64:
  extends: .mutter.fedora:33@common
  variables:
    FDO_DISTRIBUTION_TAG: 'aarch64-2020-11-07.0'
  tags:
    - aarch64

build-fedora-container@x86_64:
  extends:
    - .fdo.container-build@fedora@x86_64
    - .mutter.fedora:33@x86_64
  stage: prep
  only:
    - merge_requests
    - /^.*$/

build-fedora-container@aarch64:
  extends:
    - .fdo.container-build@fedora@aarch64
    - .mutter.fedora:33@aarch64
  stage: prep
  only:
    - merge_requests
    - /^.*$/

check-commit-log:
  extends:
    - .fdo.distribution-image@fedora
    - .mutter.fedora:33@x86_64
  stage: review
  variables:
    GIT_DEPTH: "100"
  script:
    - ./.gitlab-ci/check-commit-log.sh
  only:
    - merge_requests

.build-mutter:
  extends:
    - .fdo.distribution-image@fedora
  stage: build
  script:
    - meson . build -Dbuildtype=debugoptimized -Db_coverage=true -Degl_device=true -Dwayland_eglstream=true --werror --prefix /usr
    - ninja -C build
    - ninja -C build install
  artifacts:
    expire_in: 1 day
    paths:
      - build
  only:
    - merge_requests
    - /^.*$/

build-mutter@x86_64:
  extends:
    - .build-mutter
    - .mutter.fedora:33@x86_64
  needs:
    - build-fedora-container@x86_64

build-mutter@aarch64:
  extends:
    - .build-mutter
    - .mutter.fedora:33@aarch64
  needs:
    - build-fedora-container@aarch64

build-without-opengl-and-glx@x86_64:
  extends:
    - .fdo.distribution-image@fedora
    - .mutter.fedora:33@x86_64
  stage: build
  needs:
    - build-fedora-container@x86_64
  script:
    - meson . build -Dbuildtype=debugoptimized -Dopengl=false -Dglx=false -Degl_device=true -Dwayland_eglstream=true --werror --prefix /usr
    - ninja -C build
    - ninja -C build install
  artifacts:
    paths:
      - build/meson-logs
  only:
    - merge_requests
    - /^.*$/

build-without-native-backend-and-wayland@x86_64:
  extends:
    - .fdo.distribution-image@fedora
    - .mutter.fedora:33@x86_64
  stage: build
  needs:
    - build-fedora-container@x86_64
  script:
    - meson . build -Dbuildtype=debugoptimized -Dnative_backend=false -Dudev=false -Dwayland=false -Dcore_tests=false --werror --prefix /usr
    - ninja -C build
    - ninja -C build install
  artifacts:
    paths:
      - build/meson-logs
  only:
    - merge_requests
    - /^.*$/

.test-mutter:
  extends:
    - .fdo.distribution-image@fedora
  stage: test
  variables:
    XDG_RUNTIME_DIR: "$CI_PROJECT_DIR/runtime-dir"
    GSETTINGS_SCHEMA_DIR: "$CI_PROJECT_DIR/build/data"
    G_SLICE: "always-malloc"
    MALLOC_CHECK_: "3"
    NO_AT_BRIDGE: "1"
  script:
    - bash -x ./.gitlab-ci/run-tests.sh
  only:
    - merge_requests
    - /^.*$/
  artifacts:
    expire_in: 1 day
    reports:
      junit: "build/${CI_JOB_NAME}-report.xml"
    name: "mutter-${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    when: always
    paths:
      - build

test-mutter@x86_64:
  extends:
    - .test-mutter
    - .mutter.fedora:33@x86_64
  needs:
    - build-mutter@x86_64
  dependencies:
    - build-mutter@x86_64

test-mutter@aarch64:
  extends:
    - .test-mutter
    - .mutter.fedora:33@aarch64
  needs:
    - build-mutter@aarch64
  dependencies:
    - build-mutter@aarch64

.test-mutter-coverage:
  extends:
    - .fdo.distribution-image@fedora
  stage: coverage
  script:
    - ninja -C build coverage
    - cat build/meson-logs/coverage.txt
  artifacts:
    paths:
      - build/meson-logs/coveragereport
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  when: always
  only:
    - merge_requests
    - /^.*$/

test-mutter-coverage@x86_64:
  extends:
    - .test-mutter-coverage
    - .mutter.fedora:33@x86_64
  needs:
    - test-mutter@x86_64
  dependencies:
    - test-mutter@x86_64

test-mutter-coverage@aarch64:
  extends:
    - .test-mutter-coverage
    - .mutter.fedora:33@aarch64
  needs:
    - test-mutter@aarch64
  dependencies:
    - test-mutter@aarch64

can-build-gnome-shell@x86_64:
  extends:
    - .fdo.distribution-image@fedora
    - .mutter.fedora:33@x86_64
  stage: test
  dependencies:
    - build-mutter@x86_64
  needs:
    - build-mutter@x86_64
  before_script:
    - meson install --no-rebuild -C build
  script:
    - .gitlab-ci/checkout-gnome-shell.sh
    - meson gnome-shell gnome-shell/build --prefix /usr -Dman=false
    - ninja -C gnome-shell/build install
  only:
    - merge_requests
    - /^.*$/
